#!/usr/bin/env node
var ed25519 = require('./ed25519')
var crypto = require('crypto')

var keypair = ed25519.keys()

process.stdout.write('export PUBLIC_KEY="' + keypair.publicKey.toString('hex') + '"\n')
process.stdout.write('export PRIVATE_KEY="' + keypair.privateKey.toString('hex') + '"\n')
